import { Member, PaymentRecord, CheckInLog, SubscriptionDuration } from './types';

export const DURATION_PRICES: Record<SubscriptionDuration, number> = {
  '1_month': 3000,
  '3_months': 8000,
  '6_months': 15000,
  '12_months': 26000,
};

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'm-1',
    memberCode: 'FF-1001',
    fullName: 'Aarav Sharma',
    email: 'aarav.sharma@gmail.com',
    phone: '9841234567',
    gender: 'Male',
    age: 26,
    joinDate: '2025-01-15',
    subscriptionStartDate: '2026-05-10',
    subscriptionEndDate: '2026-08-10',
    currentDuration: '3_months',
    paymentStatus: 'paid',
    amountDue: 0,
    emergencyContact: 'Ramesh Sharma (Father) - 9801122334',
    fitnessGoal: 'Hypertrophy & Upper Body Strength',
    notes: 'Focus on bench press technique and bicep volume.',
    lastPaymentDate: '2026-05-10',
  },
  {
    id: 'm-2',
    memberCode: 'FF-1002',
    fullName: 'Sita Adhikari',
    email: 'sita.adhikari@yahoo.com',
    phone: '9851098765',
    gender: 'Female',
    age: 24,
    joinDate: '2025-03-01',
    subscriptionStartDate: '2026-06-01',
    subscriptionEndDate: '2026-09-01',
    currentDuration: '3_months',
    paymentStatus: 'paid',
    amountDue: 0,
    emergencyContact: 'Maya Adhikari (Sister) - 9841000000',
    fitnessGoal: 'Glute & Leg Sculpting, Weight Loss',
    notes: 'Prefers dumbbell hip thrusts & squat variations.',
    lastPaymentDate: '2026-06-01',
  },
  {
    id: 'm-3',
    memberCode: 'FF-1003',
    fullName: 'Rohan Thapa',
    email: 'rohan.thapa@gmail.com',
    phone: '9801239876',
    gender: 'Male',
    age: 29,
    joinDate: '2024-11-20',
    subscriptionStartDate: '2026-02-15',
    subscriptionEndDate: '2026-08-15',
    currentDuration: '6_months',
    paymentStatus: 'paid',
    amountDue: 0,
    emergencyContact: 'Bipin Thapa (Brother) - 9812345678',
    fitnessGoal: 'Fat Loss & Core Conditioning',
    notes: 'Incorporate HIIT and abs workouts at end of session.',
    lastPaymentDate: '2026-02-15',
  },
  {
    id: 'm-4',
    memberCode: 'FF-1004',
    fullName: 'Priya Karki',
    email: 'priya.karki@outlook.com',
    phone: '9860112233',
    gender: 'Female',
    age: 22,
    joinDate: '2026-07-01',
    subscriptionStartDate: '2026-07-01',
    subscriptionEndDate: '2026-08-01',
    currentDuration: '1_month',
    paymentStatus: 'pending',
    amountDue: 3000,
    emergencyContact: 'Sunil Karki (Father) - 9841112233',
    fitnessGoal: 'General Endurance & Toning',
    notes: 'Beginner - needs guidance on resistance machines.',
    lastPaymentDate: '',
  },
  {
    id: 'm-5',
    memberCode: 'FF-1005',
    fullName: 'Kiran Shrestha',
    email: 'biatasamrat31@gmail.com',
    phone: '9811223344',
    gender: 'Male',
    age: 27,
    joinDate: '2025-06-10',
    subscriptionStartDate: '2026-05-01',
    subscriptionEndDate: '2026-11-01',
    currentDuration: '6_months',
    paymentStatus: 'paid',
    amountDue: 0,
    emergencyContact: 'Anu Shrestha (Spouse) - 9800998877',
    fitnessGoal: 'Powerlifting & Athletic Performance',
    notes: 'Heavy compound lifts (Deadlift, Squat, Bench Press).',
    lastPaymentDate: '2026-05-01',
  },
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    memberId: 'm-1',
    memberName: 'Aarav Sharma',
    amount: 8000,
    duration: '3_months',
    paymentDate: '2026-05-10',
    paymentMethod: 'eSewa',
    status: 'paid',
    receiptNumber: 'REC-2026-10492',
  },
  {
    id: 'pay-2',
    memberId: 'm-2',
    memberName: 'Sita Adhikari',
    amount: 8000,
    duration: '3_months',
    paymentDate: '2026-06-01',
    paymentMethod: 'Khalti',
    status: 'paid',
    receiptNumber: 'REC-2026-11083',
  },
  {
    id: 'pay-3',
    memberId: 'm-3',
    memberName: 'Rohan Thapa',
    amount: 15000,
    duration: '6_months',
    paymentDate: '2026-02-15',
    paymentMethod: 'Card',
    status: 'paid',
    receiptNumber: 'REC-2026-09231',
  },
  {
    id: 'pay-4',
    memberId: 'm-5',
    memberName: 'Kiran Shrestha',
    amount: 15000,
    duration: '6_months',
    paymentDate: '2026-05-01',
    paymentMethod: 'eSewa',
    status: 'paid',
    receiptNumber: 'REC-2026-10842',
  },
];

export const INITIAL_CHECKINS: CheckInLog[] = [
  {
    id: 'chk-1',
    memberId: 'm-1',
    memberName: 'Aarav Sharma',
    checkInTime: '2026-08-12 06:45 AM',
    notes: 'Chest & Triceps Morning Workout',
  },
  {
    id: 'chk-2',
    memberId: 'm-2',
    memberName: 'Sita Adhikari',
    checkInTime: '2026-08-12 07:15 AM',
    notes: 'Lower Body & Leg Day Routine',
  },
  {
    id: 'chk-3',
    memberId: 'm-5',
    memberName: 'Kiran Shrestha',
    checkInTime: '2026-08-12 08:00 AM',
    notes: 'Back & Biceps Heavy Session',
  },
];
